### ISSUE TITLE
Hubot as member for Direct Messages

### ISSUE THREAD

**Issue by thanosk** [renanvicente/hubot-mattermost#16]
Is it possible to have hubot appear as another member in mattermost, thus enable sending (private) Direct Messages to it? 

I'm trying to mimic the way Hubot integrates with Slack, which supports the above-mentioned capability.

**Comment by rompic** [comment]
+1

**Comment by rompic** [comment]
https://github.com/loafoe/hubot-matteruser claims to do that

**Comment by thanosk** [comment]
oh thanks @rompic it indeed does what it claims, so no need for this issue anymore.
