### ISSUE TITLE
Add support for multiple tokens

### ISSUE THREAD

**Issue by henriwi** [renanvicente/hubot-mattermost#2]
To support Hubot running in multiple channels, the Hubot adapter need to support multiple mattermost tokens.

Ref.: https://twitter.com/heitor_lessa/status/664513773919739904

**Comment by heitorlessa** [comment]
Working on it...

**Comment by mindlapse** [comment]
Looking forward to it!

**Comment by heitorlessa** [comment]
That is now complete and README has been updated.
