### ISSUE TITLE
Running Hubot on a Non-standard Port via Mattermost with SSL

### ISSUE THREAD

**Issue by swannysec** [renanvicente/hubot-mattermost#9]
Renan,

I'm running hubot on a non-standard port because another application is running on 8080.  Additionally, I have Mattermost running over SSL with a non-self signed cert.  I can't quite seem to get hubot working.  I have it running without complaint, but calling hubot in the designated channel doesn't result in anything occurring.

The two variables of interest are:

MATTERMOST_ENDPOINT=http://127.0.0.1:PORT/subot/incoming
MATTERMOST_INCOME_URL=https://mysite.mydomain.tld/hooks/mytoken

I've tried a bunch of combinations of url structures and have not had any luck so far.

Any thoughts?

**Comment by renanvicente** [comment]
The hubot port is specified in mattermost not in hubot.
when you are creating your outgoing webhook you should specify 

```
http://yourhubotip:yourhubotport/subot/incoming
```

then you should have the something similar to:

```
export MATTERMOST_ENDPOINT=/subot/incoming
export MATTERMOST_TOKEN=yourtokenforoutgoing
export MATTERMOST_INCOME_URL=https://mysite.mydomain.tld/hooks/mytoken
```

Since you have Mattermost running over SSL with a non-self signed cert you also need 

```
export MATTERMOST_SELFSIGNED_CERT=true
```

**Comment by swannysec** [comment]
Ah!  I think the last line was it!  Thank you very much, working like a charm.
